version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::779683736878:user/devuser1"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::779683736878:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-12CK9IEUCWS0A"
cloudformation_execution_role = "arn:aws:iam::779683736878:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-1TXN80IUMXVFL"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-1dwa2g56ak5t7"
image_repository = ""
region = "us-east-1"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::779683736878:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-HY23QV3V0O98"
cloudformation_execution_role = "arn:aws:iam::779683736878:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-Y01BOO0H1505"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-i9t2ilmijyl6"
image_repository = ""
region = "us-east-1"
