version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::779683736878:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-1FOGJ1622HTT4"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::779683736878:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-1N6ILOF43PDRL"
cloudformation_execution_role = "arn:aws:iam::779683736878:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-XQ0IB2ZSNYS3"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-oq6rghnn07cc"
image_repository = ""
region = "us-east-1"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::779683736878:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-1V25WIXSUS3W0"
cloudformation_execution_role = "arn:aws:iam::779683736878:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-94LZO5ME3841"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-9u2e60us3oho"
image_repository = ""
region = "us-east-1"
