version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-pipeline"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-kj0a62acgr06"
s3_prefix = "sam-pipeline-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
